fn main() {
    panic!("Completly failed!");
}

